version: '3.5'

services:
  haystack:
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./frontend/node_modules:/app/frontend/node_modules
    command: npm start

  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql/conf:/etc/postgresql/
    ports:
      - 5432:5432
    networks:
      - haystack-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    env_file: .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - haystack-network
volumes:
  postgres: