/** Declaration file generated by dts-gen */

export = async_redis;

declare function async_redis(args: any): any;

declare namespace async_redis {
    function createClient(args: any): void;

    function decorate(redisClient: any): any;

}

